openapi: 3.0.0
info:
  title: 商户开发者文档
  version: 1.0.0
  description: ""

servers:
  - url: https://api.example.com
    description: 生产环境网关地址（联系客服获取实际地址）

components:
  securitySchemes:
    merchantID:
      type: apiKey
      in: header
      name: X-Merchant-ID
      description: 商户ID，在商户后台获取
    timestamp:
      type: apiKey
      in: header
      name: X-Timestamp
      description: 当前时间戳单位为秒，误差不能超过5分钟
    signature:
      type: apiKey
      in: header
      name: X-Signature
      description: |
        签名，采用HMAC-SHA256算法，使用商户密钥对请求进行签名
        > **`X-Signature` 签名算法**  
        > 采用 **HMAC-SHA256** 算法，使用分配的商户密钥进行签名（商户秘钥及 merchantID 在商户后台获取）
        >
        > **GET 请求签名构造**
        > ```
        > 待签名字符串 = merchantID + timestamp + query_params
        > 请求示例: https://api.example.com/v1/query?param1=value1&param2=value2
        > ```
        >
        > **POST 请求签名构造**
        > ```
        > 待签名字符串 = merchantID + timestamp + query_params + request_body
        > 请求示例: https://api.example.com/v1/create?param1=value1
        > 请求体: {"name": "test","value": "123"}
        > ```
        >
        > **提示**
        > - query_params 参数按 key 升序排序，其值进行 URL 编码
        > - POST 请求体必须是 JSON 格式（无需格式化）
        > - 时间戳误差不能超过 5 分钟
        > - 签名结果大小写敏感
  
  schemas:
    OrderStatus:
      type: integer
      description: >
        订单状态码:
          * `1` - 待支付
          * `2` - 已支付
          * `3` - 已完成
          * `4` - 已失败
          * `5` - 已取消
          * `6` - 申诉中
          * `7` - 待释放

    CallbackType:
      type: string
      description: >
        回调通知类型:
          * `ORDER_CALLBACK_PENDING` - 订单进行中
          * `ORDER_CALLBACK_CANCEL` - 订单取消
          * `ORDER_CALLBACK_COMPLETED` - 订单完成
          * `ORDER_CALLBACK_PAID` - 订单已支付
          * `ORDER_CALLBACK_DISPUTE_RESULT` - 订单申诉处理结果
          * `ORDER_CALLBACK_RELEASING` - 释放代币

    DisputeResultAction:
      type: integer
      enum: [1, 2, 3]
      description: >
        申诉处理结果
          * `1` - 驳回申诉
          * `2` - 取消订单
          * `3` - 完成订单

  responses:
    Success:
      description: 成功响应（业务状态码在 code 字段中）
      content:
        application/json:
          schema:
            oneOf:
              - type: object
                description: 成功
                properties:
                  code:
                    type: integer
                    enum: [200]
                    description: 业务成功
                  data:
                    type: object
                  msg:
                    type: string
                required:
                  - code
                  - data
                  - msg
              - type: object
                description: 业务异常
                properties:
                  code:
                    type: integer
                  data:
                    type: string
                  msg:
                    type: string
                required:
                  - code
                  - data
                  - msg

    Unauthorized:
      description: 未授权
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 401
              msg:
                type: string
                example: "未授权"
              data:
                type: string
                example: ""
            required:
              - code
              - msg

    Forbidden:
      description: 权限不足
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 403
              msg:
                type: string
                example: "权限不足"
              data:
                type: string
                example: ""
            required:
              - code
              - msg

    NotFound:
      description: 资源不存在
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 404
              msg:
                type: string
                example: "资源不存在"
              data:
                type: string
                example: ""
            required:
              - code
              - msg

security:
  - merchantID: []
    timestamp: []
    signature: []

paths:
  /v1/exchange/ad/order/match:
    post:
      summary: 发起交易
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbolid:
                  type: integer
                  description: 代币符号ID，固定值：102
                finance_no:
                  type: string
                  description: 通道标识，商户后台获取
                finance:
                  type: object
                  description: 付款信息
                  properties:
                    html_field:
                      type: object
                      description: 通道参数
                      properties:
                        userName:
                          type: string
                          description: 付款人姓名
                method:
                  type: string
                  description: 撮合方式，固定值：api
                out_orderno:
                  type: string
                  description: 商户订单号
                amount:
                  type: string
                  description: 金额(元)
                attach_params:
                  type: string
                  description: 透传值，回调时原样返回
              required:
                - symbolid
                - finance_no
                - finance
                - method
                - out_orderno
                - amount
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    enum: [200]
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      orderno:
                        type: string
                        description: 系统订单号
                      out_orderno:
                        type: string
                        nullable: true
                        description: 商户订单号
                      business:
                        type: integer
                        description: 业务类型
                      cancel_reason:
                        type: string
                        description: 取消原因
                      status:
                        $ref: '#/components/schemas/OrderStatus'
                      settlement:
                        type: object
                        description: 结算信息
                      expire_at:
                        type: string
                        format: date-time
                        description: 过期时间
                      release_at:
                        type: string
                        format: date-time
                        nullable: true
                        description: 释放时间
                      completed_at:
                        type: string
                        format: date-time
                        nullable: true
                        description: 完成时间
                      paid_at:
                        type: string
                        format: date-time
                        nullable: true
                        description: 支付时间
                      created_at:
                        type: string
                        format: date-time
                        description: 创建时间
                required:
                  - code
                  - data
                  - msg
  /v1/exchange/ad/merchant/sell/up:
    post:
      summary: 发起代付
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbolid:
                  type: integer
                  description: 代币符号ID，固定值：104
                finance:
                  type: object
                  description: 收款信息
                  properties:
                    finance_no:
                      type: string
                      description: 通道标识
                    html_field:
                      type: object
                      description: 通道参数
                      oneOf:
                        - type: object
                          title: 支付宝
                          properties:
                            bank_no:
                              type: string
                              description: 支付宝账号
                            bank_name:
                              type: string
                              enum: ["支付宝"]
                              description: 支付方式
                            receiver:
                              type: string
                              description: 收款人姓名
                          required:
                            - bank_no
                            - bank_name
                            - receiver
                        - type: object
                          title: 银行卡
                          properties:
                            bank_no:
                              type: string
                              description: 银行卡账号
                            bank_name:
                              type: string
                              enum: ["银行卡"]
                              description: 支付方式
                            receiver:
                              type: string
                              description: 收款人姓名
                          required:
                            - bank_no
                            - bank_name
                            - receiver
                method:
                  type: string
                  description: 撮合方式，固定值：api
                out_orderno:
                  type: string
                  description: 商户订单号
                amount:
                  type: string
                  description: 金额(元)
                attach_params:
                  type: string
                  description: 透传值，回调时原样返回
              required:
                - symbolid
                - finance
                - method
                - out_orderno
                - amount
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    enum: [200]
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      ad:
                        type: object
                        properties:
                          id:
                            type: integer
                            description: 代付单ID
                      order:
                        type: object
                        properties:
                          orderno:
                            type: string
                            description: 系统订单号
                          status:
                            $ref: '#/components/schemas/OrderStatus'
                          out_orderno:
                            type: string
                            description: 商户订单号
                required:
                  - code
                  - data
                  - msg
  /v1/exchange/order/detail:
    get:
      summary: 订单查询
      parameters:
        - name: orderno
          in: query
          required: false
          schema:
            type: string
          description: 系统单号，与商户单号二选一
        - name: out_orderno
          in: query
          required: false
          schema:
            type: string
          description: 商户单号，与系统单号二选一
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    enum: [200]
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      orderno:
                        type: string
                        description: 系统订单号
                      out_orderno:
                        type: string
                        nullable: true
                        description: 商户订单号
                      business:
                        type: integer
                        description: 业务类型
                      cancel_reason:
                        type: string
                        description: 取消原因
                      status:
                        $ref: '#/components/schemas/OrderStatus'
                      settlement:
                        type: object
                        properties:
                          m_fee:
                            type: string
                            description: 手续费
                          m_rate:
                            type: string
                            description: 费率
                          m_amount_fee:
                            type: string
                            description: 金额手续费
                          m_service_fee:
                            type: string
                            description: 服务费
                      body:
                        type: object
                        properties:
                          pay_url:
                            type: string
                            description: 支付链接
                      expire_at:
                        type: string
                        format: date-time
                        description: 过期时间
                      release_at:
                        type: string
                        format: date-time
                        nullable: true
                        description: 释放时间
                      completed_at:
                        type: string
                        format: date-time
                        nullable: true
                        description: 完成时间
                      paid_at:
                        type: string
                        format: date-time
                        nullable: true
                        description: 支付时间
                required:
                  - code
                  - data
                  - msg
  /merchant/callback:   # 这里用示例路径，商户可自行替换
    post:
      summary: 回调通知
      # 回调接口不需要认证，因为它是平台向商户发送通知
      security: []  # 覆盖全局安全配置，设置为无认证
      description: |
        - 商户需进入 **商户系统后台 → 安全中心 → 设置回调地址** 配置回调通知 URL。
        - 平台会将订单状态通过 HTTP POST 回调至商户系统。
        - 商户收到回调后，必须返回大写字符串 `SUCCESS` 以表示确认（ACK）收到回调。

        **重试机制**
        
        平台在向回调接口推送消息时，若出现以下任一情况，将视为回调失败：
        1. 接口响应超时（默认 15 秒）
        2. HTTP 状态码非 200
        3. 响应内容未包含 `"SUCCESS"`（区分大小写）

        回调失败的消息会进入重试队列，延迟时间会逐步递增：10 秒 → 30 秒 → 1 分钟 → 2 分钟 → 5 分钟 → … → 最长 2 小时，最多重试 **16 次**。  
        若连续 16 次均失败，该消息将停止自动回调。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  $ref: '#/components/schemas/CallbackType'
                business:
                  type: integer
                  enum: [3, 4]
                  description: >
                    业务类型
                      - `3` - 交易
                      - `4` -  代付
                adno:
                  type: string
                  description: 代付单号
                orderno:
                  type: string
                  description: 订单号
                out_orderno:
                  type: string
                  description: 商户订单号
                attach_params:
                  type: string
                  description: 透传值，回调时原样返回
                dispute_result_action:
                  $ref: '#/components/schemas/DisputeResultAction'
              required:
                - type
                - business
                - adno
                - orderno
                - out_orderno
                - attach_params
      responses:
        '200':
          description: 返回大写字符串 `SUCCESS` 以表示确认（ACK）收到回调
          content:
            text/plain:
              schema:
                type: string
                enum: ["SUCCESS"]

